### ISSUE TITLE
"Something" (apart from temples) generates score for a tribe at the beginning of each turn

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#104]
Find out what it is and implement it

**Comment by rovenr12** [comment]
It is Parks: 250 points each

**Comment by GAIGResearch** [comment]
Thanks @rovenr12 that's very useful!

In fact, I think I've figured out what was happening. In the actual game, the score seems to change at beginning of the turn from a value A to a value B. But if you don't do anything at all, in the next turn you see again how the score goes from the same A to the same B (?). It's likely to be a bug in the game.

I've also noticed how temples really work. They don't actually give points every turn, but instead they provide points only:
 - when they are built (100pts)
 - when they level up (taking 3 turns to level up). 
 - Max. level is 5, and when after the turn level 5 is reached, no more points are given by the temple.
