### ISSUE TITLE
Savegames

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#127]
We need functionality to saving/loading gamestates. Ideally in a human readable format (i.e. JSON).

**Comment by rovenr12** [comment]
We can use Jackson to save the gs, while **it has problem in serializing random generator.**

The following shows how to save the board to Json file.
        ObjectMapper mapper = new ObjectMapper();
        try{
            String json = mapper.writeValueAsString(gs.getBoard());
            System.out.println("ResultingJSONstring = " + json);
        }catch (JsonProcessingException e){
            e.printStackTrace();
        }

output of first endgame:
ResultingJSONstring = {"units":[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],"tribes":[{"actorId":0,"tribeId":0,"position":null,"citiesID":[1],"capitalID":1,"techTree":{"everythingResearched":false},"stars":5,"winner":"INCOMPLETE","score":515,"obsGrid":[[false,false,false,false,false,false,false,false,false,true,true,true,true,true,false,false],[false,false,false,false,false,false,false,false,false,true,true,true,true,true,false,false],[false,false,false,false,false,false,false,false,false,true,true,true,true,true,false,false],[false,false,false,false,false,false,false,false,false,true,true,true,true,true,false,false],[false,false,false,false,false,false,false,false,false,true,true,true,true,true,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]],"tribesMet":[],"extraUnits":[],"totalProduction":2,"name":"Xin-Xi","type":"XIN_XI","reverseScore":-515,"numKills":0,"initialTechnology":"CLIMBING"},{"actorId":1,"tribeId":1,"position":null,"citiesID":[3],"capitalID":3,"techTree":{"everythingResearched":false},"stars":5,"winner":"INCOMPLETE","score":820,"obsGrid":[[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false],[true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false],[true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false],[true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false],[true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]],"tribesMet":[],"extraUnits":[],"totalProduction":0,"name":"Imperius","type":"IMPERIUS","reverseScore":-820,"numKills":0,"initialTechnology":"ORGANIZATION"},{"actorId":2,"tribeId":2,"position":null,"citiesID":[5],"capitalID":5,"techTree":{"everythingResearched":false},"stars":5,"winner":"INCOMPLETE","score":820,"obsGrid":[[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,true,true,true,true,true,false,false,false,false,false],[false,false,false,false,false,false,true,true,true,true,true,false,false,false,false,false],[false,false,false,false,false,false,true,true,true,true,true,false,false,false,false,false],[false,false,false,false,false,false,true,true,true,true,true,false,false,false,false,false],[false,false,false,false,false,false,true,true,true,true,true,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]],"tribesMet":[],"extraUnits":[],"totalProduction":0,"name":"Bardur","type":"BARDUR","reverseScore":-820,"numKills":0,"initialTechnology":"HUNTING"},{"actorId":3,"tribeId":3,"position":null,"citiesID":[7],"capitalID":7,"techTree":{"everythingResearched":false},"stars":5,"winner":"INCOMPLETE","score":825,"obsGrid":[[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true],[false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true],[false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true],[false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true],[false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]],"tribesMet":[],"extraUnits":[],"totalProduction":0,"name":"Oumaji","type":"OUMAJI","reverseScore":-825,"numKills":0,"initialTechnology":"RIDING"}],"size":16,"activeTribeID":0}

[Tutorial](https://blog.codota.com/how-to-convert-a-java-object-into-a-json-string/)

**Comment by rovenr12** [comment]
In order to use jackson

1. Download jackson
[jackson-core-2.11.0.rc1](https://github.com/FasterXML/jackson-core/releases/tag/jackson-core-2.11.0.rc1)

2. Add the library

3. Create pom.xsl under .idea/libraries
pom.xsl

<xsl:stylesheet` version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:template match="/">
    </xsl:template>

    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>2.9.8</version>
    </dependency>

</xsl:stylesheet>

**Comment by rovenr12** [comment]
**Need to have a way to store all the actors and their type as the board only store IDs**
@GAIGResearch

**Comment by GAIGResearch** [comment]
Why is this needed? To load a savegame?
Would having an actor type (i.e. of a new enum with values TRIBE, CITY, UNIT) in Actor, which is initialized in the constructor of each subclass, work?

**Comment by rovenr12** [comment]
Yes, this might be useful for loading games because the board only store the ID for cities and units. It will cause a problem in load games because there are no actors, cities and units. 

The things need to do is also store all the actor information and load it. Moreover, Is it possible to retrieve all the cities and units class in order to store it?

**Comment by GAIGResearch** [comment]
If the saving process is manual, yes. You can retrieve the agents one by one from the gameActors hashmap and using 'instanceof' you can determine the actual class of the actor.

**Comment by rovenr12** [comment]
Please download this package
https://github.com/stleary/JSON-java

**Comment by GAIGResearch** [comment]
@rovenr12 I got this random exception coming from the JSON stuff:

Game seed: 1587562911963, random seed: 1587562911963
Exception in thread "main" org.json.JSONException: JSONObject["level"] not found.
	at org.json.JSONObject.get(JSONObject.java:573)
	at org.json.JSONObject.getNumber(JSONObject.java:712)
	at org.json.JSONObject.getInt(JSONObject.java:735)
	at core.actors.Temple.<init>(Temple.java:21)
	at core.actors.City.<init>(City.java:60)
	at core.game.GameLoader.loadCities(GameLoader.java:99)
	at core.game.GameLoader.<init>(GameLoader.java:54)
	at core.game.Game.tick(Game.java:198)
	at core.game.Game.run(Game.java:163)
	at Run.runGame(Run.java:28)
	at Play.play(Play.java:68)
	at Play.main(Play.java:41)

**Comment by rovenr12** [comment]
Fixed

**Comment by GAIGResearch** [comment]
Thanks @rovenr12! PR merged.

**Comment by rovenr12** [comment]
@GAIGResearch 

Hi, I have implemented the load game, it seems fine. but when I tried to end turn, it will show the tribe array is out of bound. But I am not sure why it happens

**Comment by GAIGResearch** [comment]
I merged master into svegame and I have so far not seen this issue. I got the following error when saving and then loading a game with 4 players (all humans, no agents):

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at core.game.GameState.<init>(GameState.java:86)
	at core.game.Game.init(Game.java:110)
	at Play.play(Play.java:69)
	at Play.main(Play.java:39)

the line is `computePlayerActions(tribes[board.getActiveTribeID()])`, and the reason is that tribes is of size 1 when it should be 4. In fact, the problem seems to be in saving, as the json file (attached as txt because github doesn't support uploading json files to comments: 
[game.txt](https://github.com/GAIGResearch/Tribes/files/4532907/game.txt)) has only one tribe with id -1?

See also screenshot:

<img width="450" alt="Screen Shot 2020-04-25 at 13 10 19" src="https://user-images.githubusercontent.com/35296018/80279522-2475d400-86f6-11ea-8651-23b912b2b0f6.png">

Not sure how could be saved like this, any idea?

**Comment by rovenr12** [comment]
I think the problem probably is in the loading part. In loading tribe, it does not link with actorID.

**Comment by GAIGResearch** [comment]
For tribes, you can use tribeId. But it's still saving only one tribe, which is also wrong on the save part, right? I have other previous savegames where it does save 4 tribes, so it does write 4 tribes sometimes.

**Comment by rovenr12** [comment]
Hi I fixed the bug, the tribe number is correct now

**Comment by GAIGResearch** [comment]
And I also found a crash:

Exception in thread "main" java.lang.ClassCastException: core.actors.City cannot be cast to core.actors.units.Unit
	at core.game.GameSaver.writeTurnFile(GameSaver.java:89)
	at core.game.Game.tick(Game.java:220)
	at core.game.Game.run(Game.java:184)
	at Run.runGame(Run.java:28)
	at Play.play(Play.java:71)
	at Play.main(Play.java:38)

It seems like some IDs where mixed up when saving and/or loading

**Comment by rovenr12** [comment]
Unsure why it happens. I tested on my computer, the userID and cityID are unique after running 20 turns and the actor counts on the board are correct

**Comment by GAIGResearch** [comment]
Okay, let's do a PR and merge. If more problems show up we can open new bug issues.
