### ISSUE TITLE
Boat Health

### ISSUE THREAD

**Issue by BKhaleque** [GAIGResearch/Tribes#212]
When a unit becomes a boat their health does not get calculated correctly. This affects the attack calculations for boats.

![image](https://user-images.githubusercontent.com/37214286/79760507-1865cd00-8318-11ea-9670-b9fbe847f2be.png)

**Comment by GAIGResearch** [comment]
The Max HP is not being copied in embark() (and actually in disembark() as well). It needs to be copied as it is done with the current HP in both methods.
