### ISSUE TITLE
Ship and Battleship health

### ISSUE THREAD

**Issue by BKhaleque** [GAIGResearch/Tribes#244]
The issue of the health being out of -1 is happening with the upgraded boats and ships. 

![Capture](https://user-images.githubusercontent.com/37214286/80862460-411d8900-8c6d-11ea-92e9-d7996366d137.PNG)
![Capture2](https://user-images.githubusercontent.com/37214286/80862461-42e74c80-8c6d-11ea-8118-50cca4823bdf.PNG)

**Comment by GAIGResearch** [comment]
Fixed now in master @BKhaleque
