### ISSUE TITLE
Game over when not all of city is lost

### ISSUE THREAD

**Issue by rovenr12** [GAIGResearch/Tribes#252]
![image](https://user-images.githubusercontent.com/59207243/81009020-c52d6780-8e4b-11ea-895f-6002d12c606c.png)

The game is over when the red tribe lost capital

**Comment by GAIGResearch** [comment]
Unless I'm missing something, this is intended behaviour. 

In the CAPITALS game mode:
 - A tribe loses when all their cities are lost
 - A tribe wins when it has captured all capitals from all the other tribes.

The game end in this situation is triggered by the second condition: two players and the yellow has conquered red's capital.
