### ISSUE TITLE
A unit can attack itself and heal.

### ISSUE THREAD

**Issue by stevemman** [GAIGResearch/Tribes#263]
When a unit is hurt it can attack itself and that heals him. The unit heals always for 2 points. This action doesnt change it's status.
**Example**
The rider here is hurt and has 4/10 hp
![bug1](https://user-images.githubusercontent.com/16674165/81817555-cc780380-9524-11ea-88a7-0c34ee4a6ddb.png)
The rider healed 2hp (same as it's attack value), and it's status is still FRESH
![bug2](https://user-images.githubusercontent.com/16674165/81817974-558f3a80-9525-11ea-8522-2f7f9e3c5c11.png)

**Comment by stevemman** [comment]
Turns out its a RECOVER action that a unit can do on itself multiple times until its back to full hp.

**Comment by GAIGResearch** [comment]
@stevemman I've just solved the first of the bugs mentioned in issue https://github.com/GAIGResearch/Tribes/issues/257. This involved fixing Unit copy methods and setting the unit status to FINISHED after executing the first time.

Changes are now in master, could you please check if this one is also fixed now or still broken?

**Comment by stevemman** [comment]
So the reason a unit could RECOVER multiple times was that `Unit.transitionToStatus()` wouldnt allow any unit to transition to FINISHED, i guess i didnt think to add it as a valid transition any unit can make. I fixed the issue now and tested it both for passive as well as active RECOVER.

**Comment by GAIGResearch** [comment]
Ah, I see the problem now. Great it's fixed now, will you do PR? Thanks!
