### ISSUE TITLE
Create more levels

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#269]
- 2-player level x4 (Tiny size - 11x11 - 121 tiles)
   - [ ] Stavros: Xin-xi Imperius
   - [ ] Bobby: Xin-xi Imperius
   - [ ] Judy: Xin-xi Imperius
   - [ ] Diego: Xin-xi Imperius 
 - 4-player level x4 (Normal size - 16x16 - 256 tiles)
   - [ ] Stavros: Xin-xi Imperius Bardur Oumaji
   - [ ] Bobby: Xin-xi Imperius Bardur Oumaji
   - [ ] Judy: Xin-xi Imperius Bardur Oumaji
   - [ ] Diego: Xin-xi Imperius Bardur Oumaji
 - 2-player sym. level (Tiny size - 11x11 - 121 tiles)

In the app: Pass & Play, Might, Map Size: Tiny/Normal

**Comment by stevemman** [comment]
I found this map generator
https://quasistellar.github.io/Polytopia-Map-Generator/

**Comment by GAIGResearch** [comment]
That's great! I guess we can't export them easily, but much better than doing it with the phone app. Looks like something to use @rovenr12 @BKhaleque

**Comment by GAIGResearch** [comment]
Actually, generating it with the 'Text output' checkbox on does produce some textual output - although it's missing the resources layer and it's shown in isometric view. But may be helpful...

**Comment by GAIGResearch** [comment]
I'll be creating these two:

![Screen Shot 2020-05-14 at 18 06 34](https://user-images.githubusercontent.com/35296018/81963986-e2152800-960d-11ea-9a71-ab73cb551e89.png)
![Screen Shot 2020-05-14 at 18 07 41](https://user-images.githubusercontent.com/35296018/81963991-e5101880-960d-11ea-9a36-168b32bb0351.png)

I think we've got the chance of getting more or less balanced levels by picking wisely. Tribes spread around and good amount of resources around the bases should do the trick.

**Comment by stevemman** [comment]
I found the generator on the Polytopia reddit page, this is the thread: 

[https://www.reddit.com/r/Polytopia/comments/ekdy2d/polytopia_map_generator/fdajlog/](url)

In the comments of the above the community manager of the game says:

> Our only concern with this is that the randomness of the terrain is part of the balance between tribes. In case you didnt know, the amount of animals, trees, water, etc are set per tribe.

I personally did not know this, i thought the changes for different tribes were only cosmetic. For those that are curious i found this sheet with all the probabilities used for the map generation.

[https://docs.google.com/spreadsheets/d/1mPWAX3gCbh4RRtHHeOwXEr5TkcBvpA18GdvuRD_VtwY/edit#gid=0](url)

**Comment by GAIGResearch** [comment]
And yet another interesting thing, the code of the map generator is here: https://github.com/QuasiStellar/Polytopia-Map-Generator

It'll take a while, but I'm very tempted to rewrite it in Java and include it to our framework... not only it would allow us to have infinite amount of levels (bringing more robust AI testing), but also would strenghten the paper as it allows for research on PCG as well.

Regarding: resources in starting positions: yes, that's right. It's done so those tribes who start with a given tech research would have the exact resources that can be gathered in the first city at the begining.
