### ISSUE TITLE
Wrong value in tribesconfig

### ISSUE THREAD

**Issue by QuasiStellar** [GAIGResearch/Tribes#274]
https://github.com/GAIGResearch/Tribes/blob/master/src/core/TribesConfig.java#L123
Not sure what you mean there but units heal 4hp while inside their borders

**Comment by GAIGResearch** [comment]
This value is used in addition to RECOVER_PLUS_HP (2+2).

**Comment by QuasiStellar** [comment]
Though, it says "IN_CITY", should be "IN_BORDERS" or smth.

**Comment by GAIGResearch** [comment]
That's a good point! Will be renamed.
