### ISSUE TITLE
Turn status in types

### ISSUE THREAD

**Issue by QuasiStellar** [GAIGResearch/Tribes#280]
https://github.com/GAIGResearch/Tribes/blob/master/src/core/Types.java#L120
There are only two states: fresh and finished. Everything else should be described by unit abilities.

**Comment by GAIGResearch** [comment]
That is correct in the game, although the framework is implemented using intermediate states to ease turn management and allow for potential new unit types.

**Comment by QuasiStellar** [comment]
How to run the code, btw?

**Comment by GAIGResearch** [comment]
The main entry point is in Play.java. There's not much documentation yet, but the main() method there allows for some basic ways of running it. Bear in mind that the main objective of this project is for AI research! :)

**Comment by QuasiStellar** [comment]
What java version does it use?
