### ISSUE TITLE
Ruins in types

### ISSUE THREAD

**Issue by QuasiStellar** [GAIGResearch/Tribes#281]
https://github.com/GAIGResearch/Tribes/blob/master/src/core/Types.java#L140
Ruins are not resources, there can be other resources under a ruin. Ruin is a separate tile characteristic.

**Comment by GAIGResearch** [comment]
Allowing ruins + resources on the same tile is not straightforward in the current implementation, it needs some work. But good to know that's possible (I actually haven't seen that in any game, I think)
