### ISSUE TITLE
Action Pack C

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#34]
- [x] Examine (unit action)
- [x] Spawn (city action)
- [x] Clear Forest (city action)
- [x] Grow Forest (city action)
- [x] Burn Forest (city action)
- [x] Destroy (city action)

**Comment by rovenr12** [comment]
I will do this :)

**Comment by rovenr12** [comment]
Examine:

Extra Function in other class
Add city Capital Number in Tribe(Influence City, Tribe, Board and LevelLoader)

**Comment by rovenr12** [comment]
Spawn:

Change Unit Enum(add Cost and Technique Requirement)

**Comment by rovenr12** [comment]
Grow Forest:

Add GetCityTiles in Board Class -> Return all the tiles belong to the specific city

**Comment by rovenr12** [comment]
Destroy:

add  subtractScore function in Tribe
add subtractPopulation, removeBuilding functions in City
