### ISSUE TITLE
[UPDATE] UNITS shifts

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#56]
When a new city is captured (from a village to city), one UNIT moves there from the capital.

If capital has UNIT == 0, then it's taken from another city (at random?)

**Comment by GAIGResearch** [comment]
Update: if a city is lost, its population moves to the capital.
If the capital is lost, it's not clear what happens to me (my observation: nothing changes)
If the capital is recovered, it's not clear either (my observation: population moves from non-capital to capital???)

**Comment by GAIGResearch** [comment]
@rovenr12 The title of this issue was wrong. This is not about "population", but about ownership of units by each city. So what we're takin g about here is how units belonging to one city pass to belong to another

**Comment by rovenr12** [comment]
just wondering what will happen if the city is lost, but the capital is also lost? what will the units go through?

**Comment by GAIGResearch** [comment]
Good question, and I'm not sure about the answer. Let's implement it like follows: if the city is lost and the capital is no longer owned, the unit ownership moves to any random city with enough space in their unitsID list.

**Comment by rovenr12** [comment]
I think that might have issues when there is not enough space in all of the cities.

**Comment by GAIGResearch** [comment]
Possibly. One of the open issues (https://github.com/GAIGResearch/Tribes/issues/70) requires having a list of units that the Tribe "owns", which in principle should have unlimited capacity. If anything else fails, we can defect to move the units there.

**Comment by rovenr12** [comment]
if the capital's space is less than the requirement, will it still move to capital?

**Comment by GAIGResearch** [comment]
Yes, I think so!

**Comment by rovenr12** [comment]
In this class, we might be able to do the same things when the capital is lost as well.
So it can be (1)move to Capital (2)move to City (3)move to the tribe(This one also means game over as the tribe does not have any cities)

**Comment by GAIGResearch** [comment]
The order is right, but it wouldn't be game over, would it? Having no space to own units doesn't mean that the tribe has no more cities, right?
