### ISSUE TITLE
Negative populations

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#63]
Populations can be negative in cities, which happens when losing connection to the capital. But I'm not 100% sure how it happens, so needs investigating.

One clear effect is that a city with -X population generates -X stars.

**Comment by rovenr12** [comment]
https://polytopia.fandom.com/wiki/Population

Negative Population (Anti-Food)
If a city ever loses population (i.e. a city disconnected from the capital, a Nature Bunny crushing a building, destroying a building) and your population bar is empty, a red-colored segment will appear in the population bar. Each red segment removes 1 star from your production. It is not possible to make less than 0 stars per turn. You can still support Units with red segments.

If your bar fills up with red dots, your production for that city will stop completely. Should you continue to lose population, the bar will begin to shrink, and you will no longer be able to support as many units.

If you were to regain the population, you would have to first remove the red segments before creating blue segments again.

**Comment by GAIGResearch** [comment]
Only thing missing is:
The Negative Population will need to change UI as well

**Comment by rdgain** [comment]
GUI updated!
