### ISSUE TITLE
City Issues

### ISSUE THREAD

**Issue by rovenr12** [GAIGResearch/Tribes#72]
If an enemy unit or Nature Bunny moves into one of your cities, star production from that city will stop entirely and you will gain 0 stars from it the next turn. **City Class**

Units in their tribe's city get a +50% (×1.5) defence buff, which increases to +300% (×4) if the city has city walls. **Defense Action**

It is also important to note that the amount of cities you own influences the prices of tech on the Technology Tree. 1 star per extra city for Tier 1, 2 stars per extra city on Tier 2 and 3 stars on Tier 3 techs.  **Technology Action**

**Comment by GAIGResearch** [comment]
Missing this:

Attack action: Units in their tribe's city get a +50% (×1.5) defence buff, which increases to +300% (×4) if the city has city walls.
