### ISSUE TITLE
Destroying a Custom House

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#73]
Destry.java, execute()

When destroying a CUSTOM HOUSE building, see:

 //TODO: Is this correct? The production of a custom house depends on the number of Ports around it,
 // so I'm not sure this should be a constant value.

city.subtractProduction(removedBuilding.getPRODUCTION());

**Comment by rovenr12** [comment]
When a building is destroyed, the city it was built in will lose the population gained by constructing the building.
but I found it should let change production updates the production as well. So I will change the production during change production ( which is triggered by building a farm, lumber_hut, mine and port  )
